workspace:
  base: /test
  path: openeuropa-site

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
      - DOCUMENT_ROOT=/test/openeuropa-site
      - COMPOSER_CACHE_DIR=/cache/composer
      - DATABASE_NAME=openeuropa_site
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
      - DATABASE_PREFIX=
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - ACCOUNT_USERNAME=admin
      - ACCOUNT_PASSWORD=admin
      - DRUPAL_ROOT=web
      - DRUPAL_BASE_URL=http://web:8080/web
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug

pipeline:
  # Download all dependencies.
  composer-install:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  # Install the drupal site.
  site-install:
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run drupal:site-install

  # Run grumphp tests.
  test-grumphp:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/grumphp run

  # Run behat tests.
  test-behat:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/behat --strict
