workspace:
  base: /test
  path: drupal-site-template

services:
  web:
    image: fpfis/httpd-php-dev:${PHP_VERSION=7.1}
    environment:
      - DOCUMENT_ROOT=/test/drupal-site-template
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug

pipeline:
  # Download all dependencies.
  composer-create-project:
    group: pre-prepare
    image: fpfis/httpd-php-full:${PHP_VERSION=7.1}
    environment:
      - DRUPAL_BASE_URL=http://web:8080/drupal-site-test/web
    volumes:
      - /cache:/cache
    commands:
      # remove the cache for internal use.
      - rm -rf /cache/composer/vcs/-test-drupal-site-template
      - composer create-project --repository-url=packages.json --ansi --no-progress --no-interaction openeuropa/drupal-site-template digit-drupal-site-test-reference

  # Initialize git.
  git-init:
    image: fpfis/httpd-php-full:7.1
    commands:
      - cd digit-drupal-site-test-reference
      - git init

  # Install the drupal site.
  site-install:
    image: fpfis/httpd-php-full:${PHP_VERSION=7.1}
    environment:
      - DRUPAL_DATABASE_NAME=openeuropa_site
      - DRUPAL_DATABASE_USERNAME=root
      - DRUPAL_DATABASE_PASSWORD=
      - DRUPAL_DATABASE_PREFIX=
      - DRUPAL_DATABASE_HOST=mysql
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_ACCOUNT_USERNAME=admin
      - DRUPAL_ACCOUNT_PASSWORD=admin
      - DRUPAL_BASE_URL=http://web:8080/drupal-site-test/web
    commands:
      - cd digit-drupal-site-test-reference
      - ./vendor/bin/run toolkit:install-clean
      - ./vendor/bin/drush cex -y

  # Run grumphp tests.
  test-grumphp:
    group: test
    image: fpfis/httpd-php-full:${PHP_VERSION=7.1}
    commands:
      - cd digit-drupal-site-test-reference
      - ./vendor/bin/grumphp run

  # Run behat tests.
  test-behat:
    group: test
    image: fpfis/httpd-php-full:${PHP_VERSION=7.1}
    commands:
      - cd digit-drupal-site-test-reference
      - ./vendor/bin/run toolkit:disable-drupal-cache
      - ./vendor/bin/behat --strict

matrix:
  PHP_VERSION:
    - 7.1
    - 7.2
    - 7.3
