workspace:
  base: /test
  path: openeuropa-site

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
      - DOCUMENT_ROOT=/test/openeuropa-site
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer install

  site-install:
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/grumphp run
    # PHP Mess Detector is throwing unreasonable errors. Remove this line once
    # OPENEUROPA-792 is fixed.
    # https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-792
    err_ignore: true

  behat:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/behat
